"""`airbag install` - wire the gate into git and into AI editors."""

from __future__ import annotations

import json
import os
import stat
import sys
from typing import List, Optional

from . import gitutil, templates

LAUNCHER_RELATIVE = os.path.join(".airbag", "hook.py")

LAUNCHER = '''#!/usr/bin/env python
"""Airbag launcher - generated by `airbag install`. Safe to commit.

Keeping the launcher in the repository means every clone gets the same gate,
whether or not Airbag is pip-installed on that machine.
"""

import os
import sys

VENDORED = r"__VENDOR__"

if VENDORED and os.path.isdir(VENDORED) and VENDORED not in sys.path:
    sys.path.insert(0, VENDORED)

try:
    from airbag.cli import main
except ImportError:
    sys.stderr.write(
        "airbag: not installed on this machine - skipping the check.\\n"
        "Install it with:\\n"
        "  pip install git+https://github.com/n-bharath-chowdary/airbag\\n"
    )
    raise SystemExit(0)

raise SystemExit(main(sys.argv[1:]))
'''


def _python() -> str:
    return (sys.executable or "python").replace("\\", "/")


def _write(path: str, content: str, force: bool, executable: bool = False) -> str:
    directory = os.path.dirname(path)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory, exist_ok=True)
    if os.path.exists(path) and not force:
        with open(path, "rb") as handle:
            existing = handle.read().decode("utf-8", "replace")
        if "Airbag" in existing or "airbag" in existing:
            return "unchanged (already installed): {}".format(_rel(path))
        return "skipped (exists, use --force): {}".format(_rel(path))

    with open(path, "wb") as handle:
        handle.write(content.replace("\r\n", "\n").encode("utf-8"))
    if executable:
        mode = os.stat(path).st_mode
        os.chmod(path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return "wrote {}".format(_rel(path))


def _rel(path: str) -> str:
    try:
        return os.path.relpath(path).replace("\\", "/")
    except ValueError:
        return path


def _hooks_dir(root: str) -> str:
    code, out, _ = gitutil.git(["config", "--get", "core.hooksPath"], cwd=root)
    if code == 0 and out.strip():
        configured = out.strip()
        return configured if os.path.isabs(configured) else os.path.join(root, configured)
    code, out, _ = gitutil.git(["rev-parse", "--git-dir"], cwd=root)
    git_dir = out.strip() if code == 0 and out.strip() else ".git"
    if not os.path.isabs(git_dir):
        git_dir = os.path.join(root, git_dir)
    return os.path.join(git_dir, "hooks")


def _importable_without_help() -> bool:
    """True when `import airbag` works in a clean interpreter.

    PYTHONPATH is stripped deliberately: a hook runs in whatever environment
    git or the editor provides, so an import that only succeeds because of the
    installing shell's PYTHONPATH does not count.
    """
    import subprocess
    import tempfile

    env = dict(os.environ)
    env.pop("PYTHONPATH", None)
    try:
        proc = subprocess.run(
            [sys.executable, "-c", "import airbag"],
            cwd=tempfile.gettempdir(),
            env=env,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except OSError:
        return False
    return proc.returncode == 0


def install_launcher(root: str, force: bool) -> List[str]:
    # Only bake in an absolute path when Airbag is not installed as a
    # package - otherwise the committed launcher would carry one developer's
    # local path around for everyone else.
    vendored = ""
    if not _importable_without_help():
        vendored = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    content = LAUNCHER.replace("__VENDOR__", vendored.replace("\\", "\\\\"))
    return [_write(os.path.join(root, LAUNCHER_RELATIVE), content, force=True, executable=True)]


def install_git(root: str, force: bool) -> List[str]:
    log = install_launcher(root, force)
    hooks = _hooks_dir(root)
    script = LAUNCHER_RELATIVE.replace("\\", "/")
    for name, template in (("pre-commit", templates.PRE_COMMIT_HOOK),
                           ("pre-push", templates.PRE_PUSH_HOOK)):
        log.append(_write(
            os.path.join(hooks, name),
            template
            .replace("__AIRBAG_PYTHON__", _python())
            .replace("__AIRBAG_SCRIPT__", script),
            force,
            executable=True,
        ))
    return log


def install_claude(root: str, force: bool) -> List[str]:
    log = install_launcher(root, force)
    # The skill teaches the agent the workflow; the hook enforces it even when
    # the agent forgets. Install both.
    log.append(_write(
        os.path.join(root, ".claude", "skills", "airbag", "SKILL.md"),
        templates.SKILL_MD,
        force,
    ))
    settings_path = os.path.join(root, ".claude", "settings.json")
    command = '"{}" "$CLAUDE_PROJECT_DIR/{}" hook claude'.format(
        _python(), LAUNCHER_RELATIVE.replace("\\", "/")
    )

    data = {}
    if os.path.isfile(settings_path):
        try:
            with open(settings_path, "rb") as handle:
                data = json.loads(handle.read().decode("utf-8", "replace") or "{}")
        except ValueError:
            return log + ["skipped: {} is not valid JSON".format(_rel(settings_path))]

    hooks = data.setdefault("hooks", {})
    pre_tool = hooks.setdefault("PreToolUse", [])
    if not isinstance(pre_tool, list):
        return log + ["skipped: hooks.PreToolUse in settings.json is not a list"]

    already = json.dumps(pre_tool).find("airbag") >= 0
    if already and not force:
        log.append("unchanged (hook already registered): {}".format(_rel(settings_path)))
        return log

    if already:
        pre_tool = [entry for entry in pre_tool if "airbag" not in json.dumps(entry)]
        hooks["PreToolUse"] = pre_tool

    pre_tool.append({
        "matcher": "Bash",
        "hooks": [{"type": "command", "command": command}],
    })

    directory = os.path.dirname(settings_path)
    if not os.path.isdir(directory):
        os.makedirs(directory, exist_ok=True)
    with open(settings_path, "wb") as handle:
        handle.write((json.dumps(data, indent=2) + "\n").encode("utf-8"))
    log.append("wrote {} (PreToolUse hook on Bash)".format(_rel(settings_path)))
    return log


def install_cursor(root: str, force: bool) -> List[str]:
    log = install_launcher(root, force)
    log.append(_write(
        os.path.join(root, ".cursor", "rules", "airbag.mdc"),
        templates.CURSOR_RULE,
        force,
    ))
    return log


def install_windsurf(root: str, force: bool) -> List[str]:
    log = install_launcher(root, force)
    log.append(_write(
        os.path.join(root, ".windsurf", "rules", "airbag.md"),
        templates.CURSOR_RULE,
        force,
    ))
    return log


def install_codex(root: str, force: bool) -> List[str]:
    """Append the Airbag section to AGENTS.md (Codex, Jules, Amp, ...)."""
    log = install_launcher(root, force)
    path = os.path.join(root, "AGENTS.md")
    section = templates.AGENTS_SECTION

    if not os.path.isfile(path):
        header = "# Agent instructions\n\n"
        with open(path, "wb") as handle:
            handle.write((header + section).encode("utf-8"))
        log.append("wrote {}".format(_rel(path)))
        return log

    with open(path, "rb") as handle:
        existing = handle.read().decode("utf-8", "replace")

    if "airbag:start" in existing:
        if not force:
            log.append("unchanged (section already present): {}".format(_rel(path)))
            return log
        start = existing.index("<!-- airbag:start -->")
        end = existing.index("<!-- airbag:end -->") + len("<!-- airbag:end -->")
        existing = existing[:start] + section.strip() + existing[end:]
    else:
        if not existing.endswith("\n"):
            existing += "\n"
        existing += "\n" + section

    with open(path, "wb") as handle:
        handle.write(existing.encode("utf-8"))
    log.append("updated {}".format(_rel(path)))
    return log


def install_ci(root: str, force: bool) -> List[str]:
    return [_write(
        os.path.join(root, ".github", "workflows", "airbag.yml"),
        templates.GITHUB_WORKFLOW,
        force,
    )]


INSTALLERS = {
    "git": install_git,
    "claude": install_claude,
    "cursor": install_cursor,
    "windsurf": install_windsurf,
    "codex": install_codex,
    "ci": install_ci,
}


def installed_hooks(root: str) -> List[str]:
    found: List[str] = []
    hooks = _hooks_dir(root)
    for name in ("pre-commit", "pre-push"):
        path = os.path.join(hooks, name)
        if os.path.isfile(path) and _mentions(path):
            found.append("git/" + name)
    checks = {
        "claude": os.path.join(root, ".claude", "settings.json"),
        "cursor": os.path.join(root, ".cursor", "rules", "airbag.mdc"),
        "windsurf": os.path.join(root, ".windsurf", "rules", "airbag.md"),
        "codex": os.path.join(root, "AGENTS.md"),
        "ci": os.path.join(root, ".github", "workflows", "airbag.yml"),
    }
    for label, path in checks.items():
        if os.path.isfile(path) and _mentions(path):
            found.append(label)
    return found


def _mentions(path: str) -> bool:
    try:
        with open(path, "rb") as handle:
            return b"airbag" in handle.read().lower()
    except OSError:
        return False


def run(args) -> int:
    root = gitutil.repo_root(getattr(args, "repo", None) or os.getcwd())
    if not root:
        print("airbag: not inside a git repository", file=sys.stderr)
        return 3

    targets = list(INSTALLERS) if args.target == "all" else [args.target]
    print("Airbag install -> {}".format(root))
    for target in targets:
        print("\n[{}]".format(target))
        try:
            for line in INSTALLERS[target](root, args.force):
                print("  " + line)
        except OSError as exc:
            print("  failed: {}".format(exc))

    print("\nDone. Verify with:  airbag doctor")
    print("Try it out with:    airbag scan")
    return 0
